# Stubs for switchyard.lib.packet.arp (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.packet import PacketHeaderBase

class Arp(PacketHeaderBase):
    operation = Undefined(Any)
    senderhwaddr = Undefined(Any)
    senderprotoaddr = Undefined(Any)
    targethwaddr = Undefined(Any)
    targetprotoaddr = Undefined(Any)
    def __init__(self): pass
    def size(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def __eq__(self, other): pass

    def next_header_class(self): pass
