# Stubs for switchyard.lib.packet.ethernet (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.packet import PacketHeaderBase

class Vlan(PacketHeaderBase):
    vlan = Undefined(Any)
    ethertype = Undefined(Any)
    def __init__(self, vlan=0, ethertype=Undefined): pass
    def from_bytes(self, raw): pass
    def to_bytes(self): pass
    def __eq__(self, other): pass
    def size(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def next_header_class(self): pass

EtherTypeClasses = Undefined(Any)

class Ethernet(PacketHeaderBase):
    def __init__(self, src=Undefined, dst=Undefined, ethertype=Undefined): pass
    def size(self): pass

    def to_bytes(self): pass
    src = Undefined(Any)
    dst = Undefined(Any)
    ethertype = Undefined(Any)
    def from_bytes(self, raw): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def __eq__(self, other): pass
