# Stubs for switchyard.lib.packet.icmpv6 (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.icmp import ICMP, ICMPEchoRequest, ICMPEchoReply

class ICMPv6(ICMP):
    def __init__(self): pass
    def checksum(self): pass
    def pre_serialize(self, raw, pkt, i): pass

class ICMPv6EchoRequest(ICMPEchoRequest): pass
class ICMPv6EchoReply(ICMPEchoReply): pass
class ICMPv6HomeAgentAddressDiscoveryRequestMessage(ICMPv6): pass
class ICMPv6HomeAgentAddressDiscoveryReplyMessage(ICMPv6): pass
class ICMPv6MobilePrefixSolicitation(ICMPv6): pass
class ICMPv6MobilePrefixAdvertisement(ICMPv6): pass

def construct_icmpv6_class_map(): pass
def construct_icmpv6_type_map(): pass

ICMPv6ClassFromType = Undefined(Any)
ICMPv6TypeFromClass = Undefined(Any)
