# Stubs for switchyard.lib.packet.icmp (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.packet import PacketHeaderBase

class ICMP(PacketHeaderBase):
    def __init__(self): pass
    def size(self): pass
    def checksum(self): pass
    def to_bytes(self, dochecksum=True): pass
    def from_bytes(self, raw): pass
    def __eq__(self, other): pass
    icmptype = Undefined(Any)
    def icmpdata(self, dataobj): pass

class ICMPData(PacketHeaderBase):
    def __init__(self): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def size(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass

    def __eq__(self, other): pass
    def __hash__(self): pass

class ICMPSourceQuench(ICMPData):
    def __init__(self): pass
    def size(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass

class ICMPRedirect(ICMPData):
    def __init__(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass

class ICMPDestinationUnreachable(ICMPData):
    def __init__(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass

class ICMPEchoRequest(ICMPData):
    def __init__(self): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def size(self): pass
    def from_bytes(self, raw): pass
    def to_bytes(self): pass
    def __eq__(self, other): pass

class ICMPEchoReply(ICMPEchoRequest): pass

class ICMPTimeExceeded(ICMPData):
    def __init__(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass

class ICMPAddressMaskRequest(ICMPData):
    def __init__(self): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def size(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass


class ICMPAddressMaskReply(ICMPAddressMaskRequest): pass
class ICMPInformationRequest(ICMPData): pass
class ICMPInformationReply(ICMPData): pass
class ICMPRouterAdvertisement(ICMPData): pass
class ICMPRouterSolicitation(ICMPData): pass
class ICMPParameterProblem(ICMPData): pass
class ICMPTimestamp(ICMPData): pass
class ICMPTimestampReply(ICMPData): pass

def construct_icmp_class_map(): pass
def construct_icmp_type_map(): pass

ICMPClassFromType = Undefined(Any)
ICMPTypeFromClass = Undefined(Any)
