# Stubs for switchyard.lib.packet.null (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.packet import PacketHeaderBase

AFTypeClasses = Undefined(Any)

class Null(PacketHeaderBase):
    def __init__(self, af=Undefined): pass
    def size(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def __eq__(self, other): pass
