# Stubs for switchyard.lib.packet.packet (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class Packet:
    def __init__(self, raw=None, first_header=None): pass
    def __len__(self): pass
    def size(self): pass
    def to_bytes(self): pass
    @staticmethod
    def from_bytes(raw, first_header): pass
    def __iadd__(self, ph): pass
    def __add__(self, pobj): pass
    def headers(self): pass
    def num_headers(self): pass
    def prepend_header(self, ph): pass
    def add_header(self, ph): pass
    def insert_header(self, idx, ph): pass
    def add_payload(self, ph): pass
    def has_header(self, hdrclass): pass
    def get_header_by_name(self, hdrname): pass
    def get_header(self, hdrclass): pass
    def get_header_index(self, hdrclass, startidx=0): pass
    def __iter__(self): pass
    def __getitem__(self, index): pass
    def __setitem__(self, index, value): pass
    def __contains__(self, obj): pass
    def __delitem__(self, index): pass
    def __eq__(self, other): pass

class PacketHeaderBase:
    def __init__(self): pass
    def __len__(self): pass
    def size(self): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, packet, i): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def __add__(self, ph): pass
    def __eq__(self, other): pass

class RawPacketContents(PacketHeaderBase):
    def __init__(self, raw=None): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def size(self): pass
    def __eq__(self, other): pass
