# Stubs for switchyard.lib.packet.ripv2 (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from enum import Enum
from switchyard.lib.packet.packet import PacketHeaderBase

class RIPCommand(Enum):
    Request = Undefined(Any)
    Reply = Undefined(Any)

class RIPRouteEntry:
    def __init__(self, address=Undefined, mask='', nexthop='', metric=16, tag=0): pass
    @staticmethod
    def size(): pass
    def to_bytes(self): pass
    @staticmethod
    def from_bytes(raw): pass
    @property
    def tag(self): pass
    @property
    def address(self): pass
    @property
    def netmask(self): pass
    @property
    def nexthop(self): pass
    @property
    def metric(self): pass

class RIPv2(PacketHeaderBase):
    command = Undefined(Any)
    domain = Undefined(Any)
    def __init__(self, raw=None): pass
    def size(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def __eq__(self, other): pass
    def __len__(self): pass
    def __getitem__(self, index): pass
    def __setitem__(self, index, routeentry): pass
    def append(self, routeentry): pass

    @property
    def version(self): pass

    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
