# Stubs for switchyard.lib.packet.tcp (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.packet import PacketHeaderBase
from enum import Enum

class TCPOption:
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def __eq__(self, other): pass

class TCPOptions(PacketHeaderBase):
    def __init__(self): pass
    def size(self): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def __eq__(self, other): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass

class TCPFlags(Enum):
    FIN = Undefined(Any)
    SYN = Undefined(Any)
    RST = Undefined(Any)
    PSH = Undefined(Any)
    ACK = Undefined(Any)
    URG = Undefined(Any)
    ECE = Undefined(Any)
    CWR = Undefined(Any)
    NS = Undefined(Any)

class TCP(PacketHeaderBase):
    srcport = Undefined(Any)
    seq = Undefined(Any)
    window = Undefined(Any)
    urgent_pointer = Undefined(Any)
    def __init__(self): pass
    def size(self): pass
    def pre_serialize(self, raw, pkt, i): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def __eq__(self, other): pass
