# Stubs for switchyard.lib.packet.udp (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet.packet import PacketHeaderBase

class UDP(PacketHeaderBase):
    srcport = Undefined(Any)
    def __init__(self): pass
    def size(self): pass
    def to_bytes(self): pass
    def from_bytes(self, raw): pass
    def __eq__(self, other): pass
    @property
    def srcport(self): pass
    @property
    def dstport(self): pass
    @srcport.setter
    def srcport(self, value): pass
    @dstport.setter
    def dstport(self, value): pass
    def next_header_class(self): pass
    def pre_serialize(self, raw, pkt, i): pass
