# Stubs for switchyard.lib.packet.util (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from switchyard.lib.packet import *

def create_ip_arp_reply(srchw, dsthw, srcip, targetip): pass
def create_ip_arp_request(srchw, srcip, targetip): pass
