# Stubs for switchyard.lib.common (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class SwitchyException(Exception):
    message = Undefined(Any)
    def __init__(self, message): pass

class ScenarioFailure(SwitchyException): pass
class Shutdown(Exception): pass
class NoPackets(Exception): pass

class Interface:
    ethaddr = Undefined(Any)
    ipaddr = Undefined(Any)
    netmask = Undefined(Any)
    def __init__(self, name, ethaddr, ipaddr, netmask=None): pass
    @property
    def name(self): pass

def setup_logging(debug): pass
def log_failure(s): pass
def log_debug(s): pass
def log_warn(s): pass
def log_info(s): pass

class LLNetBase:
    devupdown_callback = Undefined(Any)
    devinfo = Undefined(Any)
    def __init__(self, name=None): pass
    def set_devupdown_callback(self, callback): pass
    def interfaces(self): pass
    def ports(self): pass
    def interface_by_name(self, name): pass
    def port_by_name(self, name): pass
    def interface_by_ipaddr(self, ipaddr): pass
    def port_by_ipaddr(self, ipaddr): pass
    def interface_by_macaddr(self, macaddr): pass
    def port_by_macaddr(self, macaddr): pass
    def recv_packet(self, timeout=None, timestamp=False): pass
    def send_packet(self, dev, packet): pass
    def shutdown(self): pass
    @property
    def name(self): pass

def make_device_list(includes, excludes): pass
