# Stubs for switchyard.lib.debug (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

in_debugger = Undefined(Any)

def disable_timer(): pass
def setup_debugger(f): pass
def debugger(): pass
