# Stubs for switchyard.lib.hostfirewall (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

class Firewall:
    def __init__(self, interfaces, rules): pass
    def __enter__(self): pass
    def __exit__(self, exctype, excvalue, traceback): pass
    @staticmethod
    def add_rule(rule): pass

class AbstractFirewall:
    def __init__(self, interfaces, rules): pass
    def block(self): pass
    def unblock(self): pass
    def add_rule(self, rule): pass

class LinuxFirewall(AbstractFirewall):
    def __init__(self, interfaces, rules): pass
    def add_rule(self, rule): pass
    def block(self): pass
    def unblock(self): pass

class MacOSFirewall(AbstractFirewall):
    def __init__(self, interfaces, rules): pass
    def add_rule(self, rule): pass
    def block(self): pass
    def unblock(self): pass
