# Stubs for switchyard.lib.socketemu (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

def gather_ports(): pass
def get_ephemeral_port(): pass
def port_in_use(p): pass

class ApplicationLayer:
    def __init__(self): pass
    @staticmethod
    def init(): pass
    @staticmethod
    def recv_from_app(timeout=0.0): pass
    @staticmethod
    def send_to_app(data, source_addr, dest_addr): pass
    @staticmethod
    def queues(): pass

def setup_switchyard_stack(proto, localaddr): pass

class socket:
    def __init__(self, family, xtype, proto=0, fileno=0): pass
    @property
    def family(self): pass
    @property
    def type(self): pass
    @property
    def proto(self): pass
    def __del__(self): pass
    def accept(self): pass
    def close(self): pass
    def bind(self, address): pass
    def connect(self, address): pass
    def connect_ex(self, address): pass
    def getpeername(self): pass
    def getsockname(self): pass
    def getsocktopt(self, option, buffersize=0): pass
    def gettimeout(self): pass
    def listen(self, backlog): pass
    def recv(self, buffersize, flags=0): pass
    def recv_into(self, *args): pass
    def recvfrom(self, buffersize, flags=0): pass
    def recvfrom_into(self, *args): pass
    def send(self, data, flags): pass
    def sendto(self, data, arg2, arg3=None): pass
    def sendall(self, data, flags): pass
    def sendmsg(self, *args): pass
    def recvmsg(self, *args): pass
    def setblocking(self, flags): pass
    def setsockopt(self, level, option, value): pass
    def settimeout(self, timeout): pass
    def shutdown(self, flag): pass
