# Stubs for switchyard.lib.textcolor (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class TextColor:
    SETUP = Undefined(Any)
    def __init__(self): pass
    @staticmethod
    def setup(): pass
    @staticmethod
    def reset(): pass
    @staticmethod
    def green(): pass
    @staticmethod
    def red(): pass
    @staticmethod
    def blue(): pass
    @staticmethod
    def cyan(): pass
    @staticmethod
    def magenta(): pass
    @staticmethod
    def yellow(): pass

def red(): pass
def green(): pass
def blue(): pass
def cyan(): pass
def magenta(): pass
def yellow(): pass
