# Stubs for switchyard.lib.topo.util (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

def humanize_bandwidth(bits): pass
def unhumanize_bandwidth(bitsstr): pass

humanize_capacity = Undefined(Any)
unhumanize_capacity = Undefined(Any)

def humanize_delay(delay): pass
def unhumanize_delay(delaystr): pass
