# Stubs for switchyard.linkem (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any

class LinkEmulator:
    expiryheap = Undefined(Any)
    inqueue = Undefined(Any)
    def __init__(self, inqueue): pass
    def shutdown(self): pass
    def run(self): pass
