# Stubs for switchyard.switchy_test (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.packet import *
from switchyard.lib.address import *
from switchyard.lib.common import *
from switchyard.lib.testing import *
from switchyard.lib.debug import *

class FakePyLLNet(LLNetBase):
    devinfo = Undefined(Any)
    scenario = Undefined(Any)
    timestamp = Undefined(Any)
    def __init__(self, scenario, name=None): pass
    @property
    def name(self): pass
    def shutdown(self): pass
    def recv_packet(self, timeout=None, timestamp=False): pass
    def send_packet(self, devname, pkt): pass

def run_tests(scenario_names, usercode_entry_point, no_pdb, verbose): pass
def main_test(compile, scenarios, usercode, dryrun, no_pdb, verbose): pass
