# Stubs for switchyard.switchy_real (Python 3.4)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Undefined, Any
from switchyard.lib.address import *
from switchyard.lib.packet import *
from switchyard.lib.pcapffi import *
from switchyard.lib.common import LLNetBase
from switchyard.lib.textcolor import *

USERMAIN = Undefined(Any)

class PyLLNet(LLNetBase):
    devs = Undefined(Any)
    devinfo = Undefined(Any)
    pcaps = Undefined(Any)
    def __init__(self, devlist, name=None): pass
    @property
    def name(self): pass
    def shutdown(self): pass
    def recv_packet(self, timeout=None, timestamp=False): pass
    def send_packet(self, dev, packet): pass

def main_real(usercode, dryrun, netobj, nopdb, verbose): pass
